# Each key is a path that the webhook responds to, including leading /
/most_basic_webhook/example:
  run: ./webhook_hit.sh

/mywebhookpath:
  run: ./github-push.sh
  github:
    secret: secret
    repo: my-repo-name
    track: master

# Recommended you use the compact format above.
/my_more_explicit_github_webhook:
  run: ./script.sh
  github:
    secret: secret #optional
    track: refs/heads/master
    repo: 'https://github.com/user/repo'
